import { createTwoFilesPatch } from "diff";
import * as fs from "fs";
import * as path from "path";
import { Provider } from "../config/providers";
import { HealProposal } from "../healer/heal";

export interface PatchResult {
  patchContent: string;
  outputPath:   string;
  summary: {
    field:        string;
    oldSelector:  string;
    newSelector:  string;
    confidence:   number;
    testedItems?: number;
  };
}

export async function generatePatch(
  provider:     Provider,
  field:        string,
  proposal:     HealProposal,
  outputDir:    string,
  testedItems?: number,
): Promise<PatchResult> {
  const providersFilePath = path.resolve(__dirname, "../../config/providers.json");
  const originalSource = fs.readFileSync(providersFilePath, "utf-8");

  const providers = JSON.parse(originalSource) as Provider[];
  const providerIdx = providers.findIndex((p) => p.id === provider.id);
  if (providerIdx === -1) {
    throw new Error(`Provider "${provider.id}" not found in providers.json`);
  }
  const fieldIdx = providers[providerIdx].fields.findIndex((f) => f.name === field);
  if (fieldIdx === -1) {
    throw new Error(`Field "${field}" not found on provider "${provider.id}"`);
  }

  const oldSelector = providers[providerIdx].fields[fieldIdx].selector;
  providers[providerIdx].fields[fieldIdx].selector = proposal.new_selector;
  const proposedSource = JSON.stringify(providers, null, 2) + "\n";

  const rawPatch = createTwoFilesPatch(
    "a/config/providers.json",
    "b/config/providers.json",
    originalSource,
    proposedSource,
    "broken",
    "healed",
  );

  const patchName = `${provider.id}-selectors.patch`;
  const header = [
    `# Generated by self-healing scraper`,
    `# Provider:   ${provider.name} (${provider.id})`,
    `# Field:      ${field}`,
    `# Old:        ${oldSelector}`,
    `# New:        ${proposal.new_selector}`,
    `# Confidence: ${proposal.confidence.toFixed(2)}`,
    `# Diagnosis:  ${proposal.diagnosis}`,
    testedItems !== undefined
      ? `# Tested:     ${testedItems} valid records with proposed selector`
      : `# Tested:     (sandbox retry not run)`,
    `#`,
    `# Apply with: git apply output/${patchName}`,
    ``,
  ].join("\n");

  const patchContent = header + rawPatch;

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = path.join(outputDir, patchName);
  fs.writeFileSync(outputPath, patchContent, "utf-8");

  return {
    patchContent,
    outputPath,
    summary: { field, oldSelector, newSelector: proposal.new_selector, confidence: proposal.confidence, testedItems },
  };
}
