import { createPatch } from "diff";
import * as fs from "fs";
import * as path from "path";
import { SelectorConfig, BookField } from "../config/selectors";
import { HealProposal } from "../healer/heal";

export interface PatchResult {
  patchContent: string;
  outputPath:   string;
  summary: {
    field:        BookField;
    oldSelector:  string;
    newSelector:  string;
    confidence:   number;
    testedBooks?: number;
  };
}

export async function generatePatch(
  currentSelectors: SelectorConfig,
  field:            BookField,
  proposal:         HealProposal,
  outputDir:        string,
  testedBooks?:     number,
): Promise<PatchResult> {
  const selectorsFilePath = path.resolve(__dirname, "../../src/config/selectors.ts");
  const originalSource = fs.readFileSync(selectorsFilePath, "utf-8");

  const oldSelector = currentSelectors[field];

  // Replace the exact string value in the source text.
  // The broken selector value appears as a quoted string on its own line.
  const proposedSource = originalSource.replace(
    new RegExp(`(\\s+${field}:\\s+)"${escapeRegex(oldSelector)}"`, "g"),
    `$1"${proposal.new_selector}"`,
  );

  if (proposedSource === originalSource) {
    throw new Error(
      `Could not locate selector value "${oldSelector}" for field "${field}" in selectors.ts`,
    );
  }

  const relativeFilename = "src/config/selectors.ts";
  const rawPatch = createPatch(
    relativeFilename,
    originalSource,
    proposedSource,
    "broken",
    "healed",
  );

  const header = [
    `# Generated by self-healing scraper`,
    `# Field:      ${field}`,
    `# Old:        ${oldSelector}`,
    `# New:        ${proposal.new_selector}`,
    `# Confidence: ${proposal.confidence.toFixed(2)}`,
    `# Diagnosis:  ${proposal.diagnosis}`,
    testedBooks !== undefined
      ? `# Tested:     ${testedBooks} valid records with proposed selector`
      : `# Tested:     (sandbox retry not run)`,
    `#`,
    `# Apply with: git apply output/selectors.patch`,
    ``,
  ].join("\n");

  const patchContent = header + rawPatch;

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = path.join(outputDir, "selectors.patch");
  fs.writeFileSync(outputPath, patchContent, "utf-8");

  return {
    patchContent,
    outputPath,
    summary: {
      field,
      oldSelector,
      newSelector:  proposal.new_selector,
      confidence:   proposal.confidence,
      testedBooks,
    },
  };
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
