import { createTwoFilesPatch } from "diff";
import * as fs from "fs";
import * as path from "path";
import { Provider } from "../config/providers";
import { HealProposal } from "../healer/heal";

export interface PatchResult {
  patchContent: string;
  outputPath:   string;
  summary: {
    field:        string;
    oldSelector:  string;
    newSelector:  string;
    confidence:   number;
    testedItems?: number;
  };
}

export async function generatePatch(
  provider:     Provider,
  field:        string,
  proposal:     HealProposal,
  outputDir:    string,
  testedItems?: number,
): Promise<PatchResult> {
  const fieldDef = provider.fields.find((f) => f.name === field);
  if (!fieldDef) {
    throw new Error(`Field "${field}" not found on provider "${provider.id}"`);
  }

  const oldSelector = fieldDef.selector;
  const originalSource = JSON.stringify([provider], null, 2) + "\n";

  const healedProvider = {
    ...provider,
    fields: provider.fields.map((f) =>
      f.name === field ? { ...f, selector: proposal.new_selector } : f
    ),
  };
  const proposedSource = JSON.stringify([healedProvider], null, 2) + "\n";

  const rawPatch = createTwoFilesPatch(
    "a/config/providers.json",
    "b/config/providers.json",
    originalSource,
    proposedSource,
    "broken",
    "healed",
  );

  const patchName = `${provider.id}-selectors.patch`;
  const header = [
    `# Generated by self-healing scraper`,
    `# Provider:   ${provider.name} (${provider.id})`,
    `# Field:      ${field}`,
    `# Old:        ${oldSelector}`,
    `# New:        ${proposal.new_selector}`,
    `# Confidence: ${proposal.confidence.toFixed(2)}`,
    `# Diagnosis:  ${proposal.diagnosis}`,
    testedItems !== undefined
      ? `# Tested:     ${testedItems} valid records with proposed selector`
      : `# Tested:     (sandbox retry not run)`,
    `#`,
    `# Apply with: git apply output/${patchName}`,
    ``,
  ].join("\n");

  const patchContent = header + rawPatch;

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const outputPath = path.join(outputDir, patchName);
  fs.writeFileSync(outputPath, patchContent, "utf-8");

  return {
    patchContent,
    outputPath,
    summary: { field, oldSelector, newSelector: proposal.new_selector, confidence: proposal.confidence, testedItems },
  };
}
